[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libvulkan-dev:$CROSS_DEB_ARCH"
]
[target.i686-unknown-freebsd]
pre-build = []
[target.x86_64-unknown-freebsd]
pre-build = []
[target.powerpc64-unknown-linux-gnu]
pre-build = []

