[package]
name = "waypipe-ffmpeg-wrapper"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.0"

[dependencies]
libloading = "0.8.5"

[build-dependencies]
bindgen = "0.70.1"
pkg-config = "0.3.31"
